Moved all functions into basic.sh lib

diff --git a/pkgbox b/pkgbox
--- a/pkgbox
+++ b/pkgbox
@@ -3,72 +3,18 @@
 set -eE  #x
 set -o pipefail		# http://petereisentraut.blogspot.de/2010/11/pipefail.html
 
-# trap non-normal exit signals: 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
-# http://fvue.nl/wiki/Bash:_Error_handling
-trap pkgbox_trap 1 2 3 15 ERR
-
-# remember initial variables on script start
+# debug: remember initial variables on script start
 __VARS="$(set -o posix; set)"
 
-# absolute location of script
+# determine absolute location of script
 declare -r PKGBOX_PATH="$(dirname "$(readlink -f "$BASH_SOURCE")")"
 
-################################################################################
+# include basic lib
+source "include/basic.sh" || { echo "Fatal error: Cannot find basic helpers" >&2; exit 1; }
 
-# print usage (stdout)
-function pkgbox_usage()
-{
-	echo "Usage: ${0##*/} [OPTION]... <ACTION> <PKGFILE>"
-}
-
-# print message (stderr) and die
-# @param string... msg
-# @param [int=1] exitcode
-function pkgbox_die()
-{
-	local exitcode=1 msg="$@"
-	
-	# use last argument as exit code if it is an integer
-	pkgbox_is_int "${@:$#}" && msg="${@:1:$# - 1}" exitcode="${@:$#}"
-	
-	pkgbox_echo "$(_sgr fg=red reverse)[pkgbox die]$(_sgr) $(_sgr bold)($exitcode)$(_sgr) $msg" >&2
-	exit $exitcode
-}
-
-# trap handler
-function pkgbox_trap()
-{
-	pkgbox_die $FUNCNAME ${10:-$?}
-}
-
-# includes functionality
-function pkgbox_include()
-{
-	local file="$PKGBOX_PATH/$1"
-	[[ -r $file && -f $file ]] || pkgbox_die "Include file '$1' not found" 2
-	
-	# FIXME: "set -e" and "trap" on working on sourced script?
-	source "$file"
-}
-
-# tests if function exists
-# @param string function name
-# @return int non-zero if function does not exist
-function pkgbox_is_function()
-{
-	declare -F "$1" >/dev/null
-}
-
-# tests if value is an integer (may be negative)
-# @param string value
-# @return int non-zero if value is not an integer
-function pkgbox_is_int()
-{
-	echo $1 | egrep '^-?[0-9]+$' >/dev/null
-}
-
-# include basic libs
-pkgbox_include "include/basic.sh"
+# trap non-normal exit signals: 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
+# http://fvue.nl/wiki/Bash:_Error_handling
+trap 'pkgbox_die $FUNCNAME ${10:-$?}' 1 2 3 15 ERR
 
 ################################################################################
 
@@ -119,7 +65,7 @@ declare -r PKGBOX_SCRIPT="$2"
 #pkgbox_is_function pkgbox_usage || pkgbox_die "pkgbox_usage is no function"
 #pkgbox_is_function foobar || pkgbox_die "foobar is no function"
 #echo ${PKGBOX_OPTS[test]}
-#pkgbox_echo -n -e "\n\nHello\t$(_sgr bold)dear$(_sgr) friend: $(_sgr reverse)"
+#pkgbox_echo -n -e "\nHello\t$(_sgr bold)dear$(_sgr) friend: welcome$(_sgr reverse)"
 
 
 
